# Nombre interno identificatorio de la aplicación de Spring Boot
spring.application.name=articulos

# Configuración de la Base de Datos MySQL (XAMPP)
# Conector a la BD  "bd_articulos"
spring.datasource.url=jdbc:mysql://localhost:3306/bd_articulos?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Estrategia de JPA / Hibernate
# "update" creará automáticamente las tablas si no existen y actualizará la estructura si cambia
spring.jpa.hibernate.ddl-auto=update

# Muestra las consultas SQL ejecutadas en la terminal (útil para desarrollo - comentariar en producción)
spring.jpa.show-sql=true
# Formatea visualmente las consultas SQL
spring.jpa.properties.hibernate.format_sql=true